package com.appacts.plugin.Models;

public final class QueryStringKeyType {
	public static final String APPLICATION_GUID = "applicationGuid";
    public static final String ACCOUNT_GUID = "accountGuid";
    public static final String MODEL = "model";
    public static final String CARRIER = "carrier";
    public static final String OPERATING_SYSTEM = "operatingSystem";
    public static final String PLATFORM_TYPE = "platformType";
    public static final String DEVICE_GUID = "deviceGuid";
    public static final String DATA = "data";
    public static final String EVENT_NAME = "eventName";
    public static final String AVAILABLE_FLASH_DRIVE_SIZE = "availableFlashDriveSize";
    public static final String AVAILABLE_MEMORY_SIZE = "availableMemorySize";
    public static final String BATTERY = "battery";
    public static final String ERROR_MESSAGE = "errorMessage";
    public static final String ERROR_STACK_TRACE = "errorStackTrace";
    public static final String ERROR_SOURCE = "errorSource";
    public static final String SCREEN_NAME = "screenName";
    public static final String DATE_CREATED = "dateCreated";
    public static final String EVENT_TYPE = "eventType";
    public static final String LENGTH = "length";
    public static final String FEEDBACK = "feedback";
    public static final String FEEDBACK_RATING_TYPE = "feedbackRatingType";
    public static final String AGE = "age";
    public static final String SEX_TYPE = "sexType";
    public static final String SYSTEM_VERSION = "systemVersion";
    public static final String LOCATION_LONGITUDE = "locationLongitude";
    public static final String LOCATION_LATITUDE = "locationLatitude";
    public static final String VERSION = "version";
    public static final String LOCATION_COUNTRY = "locationCountry";
    public static final String LOCATION_COUNTRY_CODE = "locationCountryCode";
    public static final String LOCATION_ADMIN = "locationAdmin";
    public static final String LOCATION_ADMIN_CODE = "locationAdminCode";
    public static final String SESSION_ID = "sessionId";
    public static final String TIME_ZONE_OFFSET = "timeZoneOffset";
    public static final String LOCALE = "locale";
    public static final String RESOLUTION_WIDTH = "resolutionWidth";
    public static final String RESOLUTION_HEIGHT = "resolutionHeight";
    public static final String MANUFACTURER = "manufacturer";
}
